### ISSUE TITLE
Add: verification material to DID Specification

### ISSUE THREAD

**Issue by SenorMonito** [allinbits/cosmos-cash#115]
As per the DID specification, verification material is a DID attribute, but not part of the base specification.

By the end of this issue, we will add verification material to the base specification:

- verification material specify keys and algorithms
- base58 encoded at the moment

NOTE: Verification materials may not be part of the final specification => this issue may not be required.

**Comment by noandrea** [comment]
verification material have been found being important to ensure 3rd party compatibility, they have been included in the DID ADR and implemented in the linked pr
