### ISSUE TITLE
Finalize version 1.0 of the DID base specification

### ISSUE THREAD

**Issue by SenorMonito** [allinbits/cosmos-cash#116]
By the end of this issue, the wrap-up tasks for version 1.0 of the DID specification will be complete. These include:

- [ ] ADR to explain design choices
- [x] Resolve misunderstood part of the spec
- [x] More than a PR review
- [x] Enhance code coverage (Although code coverage is more than enough)
- [x] Ensure compliance to Cosmos-SDK tech best practices

**Comment by noandrea** [comment]
The ADR part will be taken care as part of #113
