### ISSUE TITLE
Produce JSON-LD according to the W3C DID Specs

### ISSUE THREAD

**Issue by noandrea** [allinbits/cosmos-cash#126]
The implementation in https://github.com/allinbits/cosmos-cash/pull/111  does not produces a compliant JSON-LD

This is due to the fact that verification relationships are stored in a map and not at root level
 
- Add a `toJSONLD()` to `types/identifier.go`
- Modify `keeper/grpc_query`
- Modify `cli/query.go`

so the output produced is compliant

**Comment by noandrea** [comment]
related to #116

**Comment by PaddyMc** [comment]
After discussing this with @noandrea we decided to change the implementation to one that relies less on proto maps and more on hardcoded fields in the proto file.

This will lead to more code, but will follow the specs more closely :thinking:
