### ISSUE TITLE
Research: Gap Analysis - USDC, USDT and Comos Cash

### ISSUE THREAD

**Issue by SenorMonito** [allinbits/cosmos-cash#160]
## Context 

All of USDC, USDT and Cosmos Cash have "Issuer" functionality that can do variations of the following:

* Mint tokens
* Burn tokens
* Freeze tokens
* Etc

Question: What are the differences between these implementations and can these be combined into a single issuer module?

## Constraints

Only consider functionality in the Solidity contract implementations. Not off-chain calls

## Assumption

The underlying assumption is that all the functionality for USDC and USDT are implemented as Smart contracts on EVM's. Check

- [USDC](https://github.com/centrehq/centre-tokens)
- USDT (can't find a GitHub repo)

## Objective

By the end of this issue there will be:

* A comparison between the different implementations
* Identify areas where there are incompatible differences
* Propose a strategy for implementing Issuer modules

## References

- [A USDT technical assessment](https://forum.makerdao.com/t/usdt-erc20-token-smart-contract-technical-assessment/3462)
- [Tether](https://tether.to/integration-guidelines/)
- [Additional USDC notes](https://www.notion.so/allinbits/USDC-Analysis-4076e0fe8ea441fb80cb9e3f7f6ef6f8)
- [Upgrading to USDC v2](https://blog.coinbase.com/usdc-v2-upgrading-a-multi-billion-dollar-erc-20-token-b57cd9437096)

**Comment by PaddyMc** [comment]
please review: :pray:

https://www.notion.so/allinbits/USDC-vs-USDT-vs-CASH-ISSUER-5e1e6530247c433292caabf4e96038bf

**Comment by SenorMonito** [comment]
Next steps: Turn this into an ADR for issuer module
