### ISSUE TITLE
Deploy the Universal resolver frontend

### ISSUE THREAD

**Issue by noandrea** [allinbits/cosmos-cash#189]

**Comment by noandrea** [comment]
It's available here: https://github.com/decentralized-identity/universal-resolver-frontend

the backend url should be updated

**Comment by SenorMonito** [comment]
@noandrea Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Cosmos-Cash-603cc33b9e3394001c927338/issues/allinbits/cosmos-cash/189?planning-poker)
