### ISSUE TITLE
Automated testnet deployment

### ISSUE THREAD

**Issue by SenorMonito** [allinbits/cosmos-cash#67]
By the end of this issue, there will be

- [x] A process that can create and build a testnet using Starport operator
- [x] The process has run and created the testnet
- [x] A transaction can be made on the testnet

[Notes here should help with the process](https://www.notion.so/allinbits/Cash-Testnet-Cash-Test-1-05ec6d04df1e4bf89ccb972e350ab930)

@helder-moreira  can also help as needed

**Comment by noandrea** [comment]
Network details:

**Nodes**: 3
- Validators: 1
- Sentry: 2

**Chain ID**: `cosmoscash-testnet`  
**Token Denom**: `cash`
**Node URL**: [cosmos-cash.app.beta.starport.cloud](https://cosmos-cash.app.beta.starport.cloud)
**Faucet URL**: [faucet.cosmos-cash.app.beta.starport.cloud](https://faucet.cosmos-cash.app.beta.starport.cloud/)
**grpc URL**:  `https://rpc.cosmos-cash.app.beta.starport.cloud:443` 
**Explorer URL**: N/A

**Comment by noandrea** [comment]
ref: https://www.notion.so/allinbits/Cash-Testnet-Cash-Test-1-05ec6d04df1e4bf89ccb972e350ab930
