### ISSUE TITLE
Automated CI/CD build

### ISSUE THREAD

**Issue by SenorMonito** [allinbits/cosmos-cash#68]
By the end of this issue, there will be an automated process that will do the following based on a GitHub check-in

- Will build project
- Run unit tests
- Run any BDD tests
- Run code coverage reports
- Run static code checks etc.
- Build documentation

**Comment by noandrea** [comment]
As general approach I will be reusing as much as possible what has been done for [gaia](https://github.com/cosmos/gaia).

**Comment by PaddyMc** [comment]
CD is completed, CI will carry over to the next sprint
