### ISSUE TITLE
Design Feature: Transfer tokens with eKYC Tx Check Golden Path v0.2

### ISSUE THREAD

**Issue by SenorMonito** [allinbits/cosmos-cash#86]
**As** a user
**I want** to transfer e-money token to another user
**So that** I can pay for another service

**As** an e-money token issuer
**I want** to ensure that transactions are only made between users that are KYC compliant
**So that** I am regulatory compliant

**User is transferring e-money tokens**
- Check proof from issuer
- is transaction less than the limit in proof
- isKYC'd
- onBeforeProccessingTransaction
- Check proof is valid

Further details are at [the Notion page](https://www.notion.so/allinbits/Feature-Transfer-tokens-with-eKYC-Tx-Check-8d3d157eb3144c928c37d740a9fc46f1)

**Comment by SenorMonito** [comment]
## V0.2 ⇒ Design sessions ⇒ Privacy respecting KYC ⇒ pair on**

    - Privacy respecting KYC
    - Research on pending tx pool
        - Transactions need to be stopped if AML profile incorrect
    - Investigate Tendermint mempool prio
    - AML, not comfortable to do, takes time
        - include in module, a sink where we dump relevant information
        - we can attach to some queue at a later date
        - can be audited later, logic can be outside the node
    - **Pending tx pool**, if approved, balance tracking
        - Issuer approves to the tx automated as an off-chain automated process
        - milliseconds
        - tool to approve
    - off chain
        - auditor that can submit something to chain flagging tx
    - KYCCredential
        - id
        - root
        - is_verified

**Comment by PaddyMc** [comment]
https://www.notion.so/allinbits/OffChain-AML-Online-AML-4f61e02e47f54b179f498d7a9c4a99bf

**Comment by noandrea** [comment]
During the design session of the 2021-06-11 we had a more detailed conversation about the requirements for compliance and it has been clarified that the requirements are that:
- transactions shall be allowed only by KYC verified parties 
- it is not required to have off-chain filters on the content of the transactions, only on-chain KYC credentials

**Comment by PaddyMc** [comment]
This issue isn't needed anymore
