### ISSUE TITLE
Explore ability to make a grpc client using rust + wasm

### ISSUE THREAD

**Issue by noandrea** [allinbits/cosmos-cash#89]

**Comment by noandrea** [comment]
The goal is to verify if it is feasible to produce an npm package built with wasm that can be used to build frontend(s) to interact with the cosmos-cash chain

**Comment by PaddyMc** [comment]
GRPC is functional

WASM version not working

Technical blockers
- TCP not supported in WASM
- Should be fixed shortly

Not going to be able to demo it till later
